id: P000449
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG6082
  title: རྩེད་ཆས་ཀུན་དགའ་ནོར་བུའི་བང་མཛོད
  author: ''
  volumes:
    0d06cbf731974a3bbc49e22fb831970a:
      image_group_id: I1KG6275
      title: Volume 1 of rtsed chas kun dga' nor bu'i bang mdzod
      volume_number: 1
      total_pages: 724
      base_file: v001.txt
ebook_metadata:
  title: རྩེད་ཆས་ཀུན་དགའ་ནོར་བུའི་བང་མཛོད
  author: ''
  sku: P000449
  cover: cover.jpg
  layers:
  - pagination
